name: Build

env:
  SKETCH_NAME: *.ino

on:
  push:
    paths:
    - '**.ino'
    - '**.cpp'
    - '**.hpp'
    - '**.h'
    - '**.c'
    - '**build.yml'
  pull_request:

jobs:
  build:
    name: ${{ matrix.fancy-name }}

    runs-on: ubuntu-latest

    strategy:
      matrix:

        arduino-boards-fqbn:
          - esp32:esp32:esp32
          - esp32:esp32:m5stack-core-esp32
          - esp32:esp32:m5stack-fire
          - esp32:esp32:m5stack-core2
          - esp32:esp32:odroid_esp32

        platform-url:
          - https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_dev_index.json

        required-libraries:
          - ESP32-Chimera-Core,Time,LovyanGFX,M5Stack-SD-Updater,Sqlite3Esp32,TinyGPSPlus,NimBLE-Arduino
          #- ESP32-Chimera-Core
          #- https://github.com/PaulStoffregen/Time/archive/master.zip
          #- LovyanGFX
          #- M5Stack-SD-Updater
          #- Sqlite3Esp32
          #- https://github.com/mikalhart/TinyGPSPlus/archive/master.zip
          #- NimBLE-Arduino


        include:
          - arduino-boards-fqbn: esp32:esp32:esp32
            fancy-name: ESP32 Generic
          - arduino-boards-fqbn: esp32:esp32:m5stack-core-esp32
            fancy-name: M5Stack
          - arduino-boards-fqbn: esp32:esp32:m5stack-core2
            fancy-name: M5Core2
          - arduino-boards-fqbn: esp32:esp32:m5stack-fire
            fancy-name: M5Fire
          - arduino-boards-fqbn: esp32:esp32:odroid_esp32
            fancy-name: OdroidGo

      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Compile example
        uses: ArminJo/arduino-test-compile@v3
        with:
          arduino-board-fqbn: ${{ matrix.arduino-boards-fqbn }}
          platform-url: ${{ matrix.platform-url }}
          required-libraries: ${{ matrix.required-libraries }}
          build-properties: ${{ toJson(matrix.build-properties) }}
          sketch-names: ${{ env.SKETCH_NAME }}
          #platform-default-url: ${{ env.PLATFORM_DEFAULT_URL }}
          #sketches-exclude: ${{ matrix.sketches-exclude }}



